[package]
name = "rust_rogue"
version = "0.1.0"
authors = ["Nunwan <perso@nunwan.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = "*"
specs = "*"
specs-derive = "*"
